name: CI

on:
  pull_request:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0

  tests:
    needs: [lint]
    name: Test ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
        python-version: ["3.9","3.11"]
        include:
          os: macos-latest
          python-version: "3.10"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install package and test requirements
        run: python -m pip install .[test]

      - run: python -m pytest
      - name: Example if statement
        if: runner.os == 'Linux':
        run: echo "This step runs only on Linux"
